name = "cfa"
description = "CLAP for Ada - thin bindings"
version = "1.2.2"
licenses = "MIT"
website = "https://github.com/ficorax/cfa"

project-files = ["cfa.gpr"]

tags = [ "ada", "cfa", "clap", "audio", "plugin",  "format" ]

authors = ["Marek Kuziel"]
maintainers = ["Marek Kuziel <ficorax@pm.me>"]
maintainers-logins = ["ficorax"]
