name = "cfa"
description = "CLAP for Ada - thin bindings"
version = "0.0.1"
licenses = "MIT"

tags = [ "cfa", "clap", "audio", "plugin",  "format" ]

authors = ["Marek Kuziel"]
maintainers = ["Marek Kuziel <ficorax@pm.me>"]
maintainers-logins = ["ficorax"]
