--  Configuration for cfa generated by Alire
pragma Restrictions (No_Elaboration_Code);

package Cfa_Config is
   pragma Pure;

   Crate_Version : constant String := "0.0.1";
   Crate_Name : constant String := "cfa";

   Alire_Host_OS : constant String := "linux";

   Alire_Host_Arch : constant String := "x86_64";

   Alire_Host_Distro : constant String := "ubuntu";

   type Build_Profile_Kind is (release, validation, development);
   Build_Profile : constant Build_Profile_Kind := development;

end Cfa_Config;
